name: Release Updates

on:
  schedule:
    # Run the workflow every Sunday at 00:00
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run update script
      run: python update_versions.py
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: |
          Update versions in README

          Automated update of versions in README.md
        branch: update-versions
        delete-branch: true
        branch-suffix: timestamp
        title: Update versions in README
        body: Automated update of versions in README.md
