name: Update README Versions

on:
  schedule:
    # Run the workflow every Sunday at 00:00
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run update script
      run: python update_versions.py
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}

    - name: Create a new branch for updates
      run: |
        git checkout -b update-versions
        git add README.md
        git commit -m "Update versions in README.md"
      env:
        GIT_AUTHOR_NAME: github-actions
        GIT_AUTHOR_EMAIL: github-actions@github.com
        GIT_COMMITTER_NAME: github-action
        GIT_COMMITTER_EMAIL: github-actions@github.com

    - name: Push changes
      run: git push origin update-versions

    - name: Set up GitHub CLI
      uses: cli/cli-action@v2

    - name: Create pull request
      run: |
        gh pr create --base main --head update-versions --title "Update versions in README" --body "Automated update of versions in README.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
